### ISSUE TITLE
AppDesigner - custom data types resetting

### ISSUE THREAD

**Issue by aubergine10** [totaljs/framework#391]
If I use a custom data type (link to another schema), for example:

![region capture 5](https://cloud.githubusercontent.com/assets/1386719/14838497/9c66c58e-0c19-11e6-9975-1f4edad33329.png)

When opening the schema to edit it, or when adding new items to it, or reordering items within it, those data types revert to 'String' as shown below:

![region capture 6](https://cloud.githubusercontent.com/assets/1386719/14838502/a29f6faa-0c19-11e6-9559-872a3dd9372a.png)

**Comment by petersirka** [comment]
Hi @aubergine10, yes I discovered this problem some time ago. I have increased script version, please refresh the webapp (CMD+R) and try it again. It must work.

Thank you!

**Comment by aubergine10** [comment]
It seems to be working better now; I'll be defining several more schemas today so will report back in several hours and confirm if the bug is fixed or not.

**Comment by petersirka** [comment]
Thank you! I use it too.

**Comment by aubergine10** [comment]
The problem seems mostly fixed, however there is one scenario where fields still get reset...

Steps to reproduce:

1. In an existing schema add a new field and fill in its details
2. Move the field further up the list - the details are reset to default values (usually empty boxes)

Workaround:

* Before moving a field, submit the schema to save all changes, then re-open and the field can be moved without losing its settings.

**Comment by aubergine10** [comment]
The bug is still present but I've tracked down more specifically what causes it to happen...

Any schemas saved to server (using "Save Schema" button in bottom right of viewport) work OK

However, schemas added after the last "Save Schema" will still exhibit problems when reordering fields that reference the 'unsaved' schemas.

Workaround:

* Before referencing a schema as field type, "Save Schema" to ensure all changes are stored on the server.

**Comment by petersirka** [comment]
Hi @aubergine10,
I have fixed it and I have added a new total.js schema types `Email`, `Zip`, `Phone`, `Camelize`, `Lower` and `Upper`. Please try it on your side.

Thank you!

**Comment by aubergine10** [comment]
The "Save Schema" button does not seem to be working. It asked for password, which I put in, then it said it had saved... reloaded and none of the changes were saved. The app is still showing v0.1.0 after clearing browser cache and reloading.

**Comment by petersirka** [comment]
Hmmm, I don't see any problem with Save Schema:
<https://designer.totaljs.com/8cc84a07dfbde59314b72fcb10ed20/>

Password: `123456`
I don't know how to simulate it.

PS: I have changed a version to `0.2.0`.
