### ISSUE TITLE
Flash message expire not working again

### ISSUE THREAD

**Issue by LeventeNagy** [totaljs/framework#487]
Hi Peter, sorry to bug you again but the Flash module expire does not work again

If I pass the expire '1 seconds' it does not work, it does not expire and just keeps duplicating the flash message, and throws the following error as well

`TypeError: F.datetime.now is not a function`

`at WebSocket.delegate_service (C:\node\tester\modules\flash.js:86:23)`

**Comment by petersirka** [comment]
Hi, sorry - my bad. I have fixed it. Please test it again.

**Comment by LeventeNagy** [comment]
Still the same now TypeError: F.datetime.now is not a function is gone, but the expire does not work
I pass exports.expire = '1 seconds'; and it does not expire after 1 second

**Comment by petersirka** [comment]
Do you use it from URL?

**Comment by LeventeNagy** [comment]
This is how I use it

Route
```
	F.route('/signup', view_signup, ['#flash']);
	F.route('/create/user', post_signup, ['post', '#flash']);
```

Controller

```
function view_signup() {
	var self = this;

	self.view('signup', { errors: self.flash() });
}

function post_signup() {
	var self = this;

	var code = rmds.generate(60);

	User.create({
		name           : self.post.name,
		email          : self.post.email,
		password       : self.post.password,
		activation_code: code
	}).then(function(data) {

		self.redirect("/welcome");

	}).catch(function(msg) {
		
		msg.errors.forEach(function(item) { 
			self.flash(item.path, item.message);
		});

		self.redirect('/signup');
	});
}

```

View

```
<div class="mdl-textfield mdl-js-textfield">
					<input class="mdl-textfield__input" type="text" name="name" id="name" />
					<label class="mdl-textfield__label mdl-color-text--black" for="name">Name</label>
					@{if model.errors.name}
						<span class="mdl-textfield__error">@{model.errors.name}</span>
					@{fi}
				</div>
```

**Comment by petersirka** [comment]
This is OK, but my question is: How did you install this module?

**Comment by LeventeNagy** [comment]
I downloaded the flash.js from GITHub and placed it in my modules folder

**Comment by petersirka** [comment]
So you can't have same problem because I fixed it:
https://github.com/totaljs/modules/blob/master/Miscellaneous/flash/flash.js#L84

**Comment by LeventeNagy** [comment]
Well I do, I set exports.expire = '1 seconds';
and it duplicates it, it does not expire

this is what i get back after the form posts
`Name cannot be empty,Name cannot be empty,Name cannot be empty,Name cannot be empty,Name cannot be empty,Name cannot be empty`

But i will solve it somehow, thank you for your time
